//
//  IO80211InfraProtocol.h
//  AirportItlwm
//
//  Created by laobamac on 2026/10/5.
//  Copyright © 2026 laobamac. All rights reserved.
//


#ifndef IO80211InfraProtocol_h
#define IO80211InfraProtocol_h

#include <IOKit/IOService.h>
#include <Airport/apple80211_var.h>
#include <Airport/apple80211_ioctl.h>

struct apple80211_sta_ie_data;
struct apple80211_sta_stats_data;
struct apple80211_rssi_bounds_data;
struct apple80211_rate_set_data;
struct apple80211_power_debug_info;
struct apple80211_bgscan_cached_network_data_list;
struct apple80211_private_mac_data;
struct apple80211_dbg_guard_time_params;
struct apple80211_ranging_enable_request_t;
struct apple80211_gas_result_t;
struct apple80211_ranging_start_request_t;
struct apple80211_leaky_ap_setting;
struct apple80211_rsdb_capability;
struct apple80211_tko_params;
struct apple80211_tko_dump;
struct apple80211_thermal_index_t;
struct apple80211_btcoex_max_nss_for_ap_data;
struct apple80211_btcoex_2g_chain_disable;
struct apple80211_power_budget_t;
struct apple80211_ranging_capabilities_t;
struct apple80211_suppress_scans_t;
struct apple80211_host_ap_mode_hidden_t;
struct apple80211_lqm_config_t;
struct apple80211_trap_mini_dump_data;
struct apple80211_beacon_info_t;
struct apple80211_softap_params;
struct apple80211_chip_power_limit;
struct apple80211_softap_stats;
struct apple80211_nss_data;
struct apple80211_hw_mac_address;
struct apple80211_he_mcs_index_set_data;
struct appl80211_chip_diags_data;
struct apple80211_hp2p_ctrl;
struct apple80211_assoc_ready;
struct apple80211_txrx_chain_info;
struct apple80211_mimo_status;
struct apple80211_dynsar_detail;
struct apple80211_mac_randomisation_status;
struct apple80211_colocated_network_scope_id
{
    uint32_t version;
    uint32_t id1;
    uint32_t id2;
};
struct apple80211_slow_wifi_feature_enabled;
struct apple80211_interface_cca_data;
struct apple80211_timesync_info;
struct apple80211_sensing_data_t;
struct apple80211_country_band_support;
struct apple80211_fw_hot_channels;
struct apple80211_low_latency_info;
struct apple80211_beacon_msg;
struct apple80211_wcl_traffic_counters;
struct apple80211_ssid_transition_feature_enabled;
typedef enum {

} p2pStatusForScan;
struct apple80211ChannelInfo;
struct apple80211_p2p_steering_metrics;;
struct apple80211_rsn_xe_data;
struct apple80211_sib_coex_status;
struct apple80211_extended_bss_info;
struct apple80211_wcl_low_latency_stats;
struct apple80211_noise_per_ant_t;
struct apple80211_blocked_bands;
struct apple80211_disassoc_data;
struct apple80211_bgscan_data;
struct apple80211_sta_authorize_data;
struct apple80211_sta_disassoc_data;
struct apple80211_rsn_conf_data;
struct apple80211_country_channel_data;
struct apple80211_awdl_forced_roam_config;
struct apple80211_offload_arp_data;
struct apple80211_offload_ndp_data;
struct apple80211_offload_scan_data;
struct apple80211_gas_query_t;
struct apple80211_gas_peer_t;
struct apple80211_btcoex_profile;
struct apple80211_btcoex_profile_active_data;
struct apple80211_trap_info_data;
struct apple80211_he_capability;
struct apple80211_pmk;
struct apple80211_wow_test_data;
struct apple80211_reset_command;
struct apple80211_crash_command;
struct apple80211_ranging_authenticate_request_t;
struct apple80211_softap_csa_params;
struct apple80211_softap_wifi_network_info;
struct apple80211_scan_control_params;
struct apple80211_usb_host_notification_data;
struct apple80211_set_mac_address;
struct apple80211_abort_scan;
struct apple80211_set_property_unserialized_data;
struct apple80211_roam_cache_data;
struct apple80211_pm_mode;
struct apple80211_wifi_assertion_data;
struct apple80211_capture_debug_info_t;
struct apple80211_linkdown_debounce_status;
struct apple80211_softap_extended_capabilities_info;
struct apple80211_sensing_enable_t;
struct apple80211_sensing_disable_t;
struct apple80211_nan_link_association_info;
struct apple80211_6G_mode;
struct apple80211_leave_network;
struct apple80211_reassoc;
struct apple80211_set_roam_lock;
struct apple80211_roam_profile_config;
struct apple80211_roam_profile_configV1;
struct apple80211_user_roam_cache;
struct apple80211_set_multi_ap_env;
struct apple80211_wcl_real_time_mode;
struct apple80211_wcl_garp_mode;
struct triggerCC;
struct apple80211ScanRequest;
struct apple80211_assoc_candidates;
struct apple80211_wcl_protect_ip_mode;
struct scanHomeAndAwayTime;
struct apple80211_wcl_voluntary_network_disconnect;
struct apple80211_wcl_update_link_state;
struct apple80211_wcl_ulofdma_state;
struct apple80211_wcl_action_frame;
struct apple80211_wcl_real_time_policy;
struct apple80211_feature_flags;
struct apple80211_dhcp_renewal_data;
struct apple80211_network_flags;
struct apple80211_battery_ps_config;
struct apple80211_mimo_config;
struct apple80211_bg_motion_profile;
struct apple80211_bg_network;
struct apple80211_bg_scan;
struct apple80211_bg_params;
struct apple80211_offload_tcpka_enable_t;

class IO80211Controller;
class CCLogStream;
#include "IO80211InfraInterface.h"
struct appl80211_sleep_on_inactivity_config;
struct apple80211AssocCandidates;
struct apple80211_associated_sleep_config;
struct apple80211_bcn_mute_config;
struct apple80211_btcoex_ext_profile;
struct apple80211_bypass_tx_power_cap;
struct apple80211_congestion_control_indication;
struct apple80211_device_accessory_info;
struct apple80211_device_orientation;
struct apple80211_drbg_entropy;
struct apple80211_dual_power_mode_params;
struct apple80211_dynamic_rssi_window_config;
struct apple80211_eap_filter_config;
struct apple80211_facetime_wificalling_params;
struct apple80211_fastlane;
struct apple80211_fw_clock_info;
struct apple80211_fw_clock_source;
struct apple80211_he_counters_ctl;
struct apple80211_host_clock_info;
struct apple80211_infra_enumerated;
struct apple80211_interface_setting;
struct apple80211_ipv4_params;
struct apple80211_ipv6_params;
struct apple80211_le_scan_params;
struct apple80211_legacy_roam_profile_config;
struct apple80211_limited_aggregation_config;
struct apple80211_lmtpc_config;
struct apple80211_lqm_statistics;
struct apple80211_mitigate_interference;
struct apple80211_mws_accessory_power_limit;
struct apple80211_mws_antenna_selection;
struct apple80211_mws_condition_id_config;
struct apple80211_mws_rfem_config;
struct apple80211_mws_scan_freq;
struct apple80211_mws_scan_freq_mode;
struct apple80211_mws_time_sharing;
struct apple80211_mws_wifi_channel_bitmap;
struct apple80211_ndd_data;
struct apple80211_os_eligibility;
struct apple80211_p2p_device_capability;
struct apple80211_power_profile;
struct apple80211_powertable_version_data;
struct apple80211_roam_profile_all_bands;
struct apple80211_sdb_enable;
struct apple80211_smartcca_opmode;
struct apple80211_standalone_state;
struct apple80211_system_sleep_config;
struct apple80211_timestamping_en;
struct apple80211_timesync_gpio;
struct apple80211_timesync_rx_policy;
struct apple80211_timesync_stats;
struct apple80211_timesync_tx_policy;
struct apple80211_traffic_eng_params;
struct apple80211_tx_mode_config;
struct apple80211_voice_ind_state;
struct apple80211_wcl_abort_join;
struct apple80211_wcl_arp_mode;
struct apple80211_wcl_qos_params;
struct apple80211_wcl_wnm_config_t;
struct apple80211_wcl_wnm_offload_t;
struct apple80211_wow_low_power_mode;
struct bss_blacklist;
struct apple80211_wifi_bt_5g_policy_t;

class IO80211InfraProtocol : public IO80211InfraInterface {
    OSDeclareAbstractStructors(IO80211InfraProtocol)
public:
    virtual IOReturn getCHANNEL(apple80211_channel_data*) = 0;
    virtual IOReturn getPOWERSAVE(apple80211_powersave_data*) = 0;
    virtual IOReturn getTXPOWER(apple80211_txpower_data*) = 0;
    virtual IOReturn getRATE(apple80211_rate_data*) = 0;
    virtual IOReturn getOP_MODE(apple80211_opmode_data*) = 0;
    virtual IOReturn getRSSI(apple80211_rssi_data*) = 0;
    virtual IOReturn getSUPPORTED_CHANNELS(apple80211_sup_channel_data*) = 0;
    virtual IOReturn getGUARD_INTERVAL(apple80211_guard_interval_data*) = 0;
    virtual IOReturn getMCS(apple80211_mcs_data*) = 0;
    virtual IOReturn getPOWER_DEBUG_INFO(apple80211_power_debug_info*) = 0;
    virtual IOReturn getHT_CAPABILITY(apple80211_ht_capability*) = 0;
    virtual IOReturn getMCS_VHT(apple80211_mcs_vht_data*) = 0;
    virtual IOReturn getCHANNELS_INFO(apple80211_channels_info*) = 0;
    virtual IOReturn getVHT_CAPABILITY(apple80211_vht_capability*) = 0;
    virtual IOReturn getROAM_PROFILE(apple80211_roam_profile_all_bands*) = 0;
    virtual IOReturn getCHIP_COUNTER_STATS(apple80211_chip_stats*) = 0;
    virtual IOReturn getDBG_GUARD_TIME_PARAMS(apple80211_dbg_guard_time_params*) = 0;
    virtual IOReturn getLEAKY_AP_STATS_MODE(apple80211_leaky_ap_setting*) = 0;
    virtual IOReturn getCOUNTRY_CHANNELS(apple80211_country_channel_data*) = 0;
    virtual IOReturn getPRIVATE_MAC(apple80211_private_mac_data*) = 0;
    virtual IOReturn getRANGING_ENABLE(apple80211_ranging_enable_request_t*) = 0;
    virtual IOReturn getRANGING_START(apple80211_ranging_start_request_t*) = 0;
    virtual IOReturn getAWDL_RSDB_CAPS(apple80211_rsdb_capability*) = 0;
    virtual IOReturn getTKO_PARAMS(apple80211_tko_params*) = 0;
    virtual IOReturn getTKO_DUMP(apple80211_tko_dump*) = 0;
    virtual IOReturn getHW_SUPPORTED_CHANNELS(apple80211_sup_channel_data*) = 0;
    virtual IOReturn getBTCOEX_PROFILE(apple80211_btcoex_profile*) = 0;
    virtual IOReturn getBTCOEX_PROFILE_ACTIVE(apple80211_btcoex_profile_active_data*) = 0;
    virtual IOReturn getTRAP_INFO(apple80211_trap_info_data*) = 0;
    virtual IOReturn getTHERMAL_INDEX(apple80211_thermal_index_t*) = 0;
    virtual IOReturn getMAX_NSS_FOR_AP(apple80211_btcoex_max_nss_for_ap_data*) = 0;
    virtual IOReturn getBTCOEX_2G_CHAIN_DISABLE(apple80211_btcoex_2g_chain_disable*) = 0;
    virtual IOReturn getPOWER_BUDGET(apple80211_power_budget_t*) = 0;
    virtual IOReturn getOFFLOAD_TCPKA_ENABLE(apple80211_offload_tcpka_enable_t*) = 0;
    virtual IOReturn getRANGING_CAPS(apple80211_ranging_capabilities_t*) = 0;
    virtual IOReturn getLQM_CONFIG(apple80211_lqm_config_t*) = 0;
    virtual IOReturn getTRAP_CRASHTRACER_MINI_DUMP(apple80211_trap_mini_dump_data*) = 0;
    virtual IOReturn getBEACON_INFO(apple80211_beacon_info_t*) = 0;
    virtual IOReturn getCHIP_POWER_RANGE(apple80211_chip_power_limit*) = 0;
    virtual IOReturn getNSS(apple80211_nss_data*) = 0;
    virtual IOReturn getHW_ADDR(apple80211_hw_mac_address*) = 0;
    virtual IOReturn getCHIP_DIAGS(appl80211_chip_diags_data*) = 0;
    virtual IOReturn getHP2P_CTRL(apple80211_hp2p_ctrl*) = 0;
    virtual IOReturn getBSS_BLACKLIST(bss_blacklist*) = 0;
    virtual IOReturn getTXRX_CHAIN_INFO(apple80211_txrx_chain_info*) = 0;
    virtual IOReturn getMIMO_STATUS(apple80211_mimo_status*) = 0;
    virtual IOReturn getCUR_PMK(apple80211_pmk*) = 0;
    virtual IOReturn getDYNSAR_DETAIL(apple80211_dynsar_detail*) = 0;
    virtual IOReturn getCOUNTRY_CHANNELS_INFO(apple80211_channels_info*) = 0;
    virtual IOReturn getLQM_SUMMARY(apple80211_lqm_summary*) = 0;
    virtual IOReturn getSLOW_WIFI_FEATURE_ENABLED(apple80211_slow_wifi_feature_enabled*) = 0;
    virtual IOReturn getTIMESYNC_INFO(apple80211_timesync_info*) = 0;
    virtual IOReturn getSENSING_DATA(apple80211_sensing_data_t*) = 0;
    virtual IOReturn getWCL_FW_HOT_CHANNELS(apple80211_fw_hot_channels*) = 0;
    virtual IOReturn getWCL_LOW_LATENCY_INFO(apple80211_low_latency_info*) = 0;
    virtual IOReturn getWCL_BSS_INFO(apple80211_beacon_msg*) = 0;
    virtual IOReturn getWCL_TRAFFIC_COUNTERS(apple80211_wcl_traffic_counters*) = 0;
    virtual IOReturn getWCL_GET_TX_BLANKING_STATUS(unsigned int*) = 0;
    virtual IOReturn getHE_COUNTERS(apple80211_he_counters_ctl*) = 0;
    virtual IOReturn getWCL_CHANNELS_INFO(apple80211ChannelInfo*) = 0;
    virtual IOReturn getRSN_XE(apple80211_rsn_xe_data*) = 0;
    virtual IOReturn getSIB_COEX_STATUS(apple80211_sib_coex_status*) = 0;
    virtual IOReturn getWIFI_BT_5G_POLICY(apple80211_wifi_bt_5g_policy_t*) = 0;
    virtual IOReturn getWCL_EXTENDED_BSS_INFO(apple80211_extended_bss_info*) = 0;
    virtual IOReturn getWCL_LOW_LATENCY_INFO_STATS(apple80211_wcl_low_latency_stats*) = 0;
    virtual IOReturn getWCL_BGSCAN_CACHE_RESULT(apple80211_bgscan_cached_network_data_list*) = 0;
    virtual IOReturn getWCL_WNM_OFFLOAD(apple80211_wcl_wnm_offload_t*) = 0;
    virtual IOReturn getWIFI_NOISE_PER_ANT(apple80211_noise_per_ant_t*) = 0;
    virtual IOReturn getFW_CLOCK_INFO(apple80211_fw_clock_info*) = 0;
    virtual IOReturn getTIMESYNC_STATS(apple80211_timesync_stats*) = 0;
    virtual IOReturn getSYSTEM_SLEEP_CONFIG(apple80211_system_sleep_config*) = 0;
    virtual IOReturn setCIPHER_KEY(apple80211_key*) = 0;
    virtual IOReturn setCHANNEL(apple80211_channel_data*) = 0;
    virtual IOReturn setPOWERSAVE(apple80211_powersave_data*) = 0;
    virtual IOReturn setTXPOWER(apple80211_txpower_data*) = 0;
    virtual IOReturn setRATE(apple80211_rate_data*) = 0;
    virtual IOReturn setIBSS_MODE(apple80211_network_data*) = 0;
    virtual IOReturn setAP_MODE(apple80211_apmode_data*) = 0;
    virtual IOReturn setIE(apple80211_ie_data*) = 0;
    virtual IOReturn setWOW_TEST(apple80211_wow_test_data*) = 0;
    virtual IOReturn setCLEAR_PMKSA_CACHE(void*) = 0;
    virtual IOReturn setVIRTUAL_IF_CREATE(apple80211_virt_if_create_data*) = 0;
    virtual IOReturn setHT_CAPABILITY(apple80211_ht_capability*) = 0;
    virtual IOReturn setOFFLOAD_ARP(apple80211_offload_arp_data*) = 0;
    virtual IOReturn setOFFLOAD_NDP(apple80211_offload_ndp_data*) = 0;
    virtual IOReturn setGAS_REQ(apple80211_gas_query_t*) = 0;
    virtual IOReturn setVHT_CAPABILITY(apple80211_vht_capability*) = 0;
    virtual IOReturn setROAM_PROFILE(apple80211_roam_profile_all_bands*) = 0;
    virtual IOReturn setDBG_GUARD_TIME_PARAMS(apple80211_dbg_guard_time_params*) = 0;
    virtual IOReturn setLEAKY_AP_STATS_MODE(apple80211_leaky_ap_setting*) = 0;
    virtual IOReturn setPRIVATE_MAC(apple80211_private_mac_data*) = 0;
    virtual IOReturn setRESET_CHIP(apple80211_reset_command*) = 0;
    virtual IOReturn setCRASH(apple80211_crash_command*) = 0;
    virtual IOReturn setRANGING_ENABLE(apple80211_ranging_enable_request_t*) = 0;
    virtual IOReturn setRANGING_START(apple80211_ranging_start_request_t*) = 0;
    virtual IOReturn setRANGING_AUTHENTICATE(apple80211_ranging_authenticate_request_t*) = 0;
    virtual IOReturn setTKO_PARAMS(apple80211_tko_params*) = 0;
    virtual IOReturn setBTCOEX_PROFILE(apple80211_btcoex_profile*) = 0;
    virtual IOReturn setBTCOEX_PROFILE_ACTIVE(apple80211_btcoex_profile_active_data*) = 0;
    virtual IOReturn setTHERMAL_INDEX(apple80211_thermal_index_t*) = 0;
    virtual IOReturn setBTCOEX_2G_CHAIN_DISABLE(apple80211_btcoex_2g_chain_disable*) = 0;
    virtual IOReturn setPOWER_BUDGET(apple80211_power_budget_t*) = 0;
    virtual IOReturn setOFFLOAD_TCPKA_ENABLE(apple80211_offload_tcpka_enable_t*) = 0;
    virtual IOReturn setLQM_CONFIG(apple80211_lqm_config_t*) = 0;
    virtual IOReturn setDYNAMIC_RSSI_WINDOW_CONFIG(apple80211_dynamic_rssi_window_config*) = 0;
    virtual IOReturn setUSB_HOST_NOTIFICATION(apple80211_usb_host_notification_data*) = 0;
    virtual IOReturn setHP2P_CTRL(apple80211_hp2p_ctrl*) = 0;
    virtual IOReturn setBSS_BLACKLIST(bss_blacklist*) = 0;
    virtual IOReturn setSET_PROPERTY(apple80211_set_property_unserialized_data*) = 0;
    virtual IOReturn setROAM_CACHE_UPDATE(apple80211_roam_cache_data*) = 0;
    virtual IOReturn setPM_MODE(apple80211_pm_mode*) = 0;
    virtual IOReturn setSET_WIFI_ASSERTION_STATE(apple80211_wifi_assertion_data*) = 0;
    virtual IOReturn setREALTIME_QOS_MSCS(apple80211_state_data*) = 0;
    virtual IOReturn setSENSING_ENABLE(apple80211_sensing_enable_t*) = 0;
    virtual IOReturn setSENSING_DISABLE(apple80211_sensing_disable_t*) = 0;
    virtual IOReturn set6G_MODE(apple80211_6G_mode*) = 0;
    virtual IOReturn setWCL_LEAVE_NETWORK(apple80211_leave_network*) = 0;
    virtual IOReturn setWCL_REASSOC(apple80211_reassoc*) = 0;
    virtual IOReturn setWCL_SET_ROAM_LOCK(apple80211_set_roam_lock*) = 0;
    virtual IOReturn setWCL_LEGACY_ROAM_PROFILE_CONFIG(apple80211_legacy_roam_profile_config*) = 0;
    virtual IOReturn setWCL_ROAM_PROFILE_CONFIG(apple80211_roam_profile_config*) = 0;
    virtual IOReturn setWCL_ROAM_USER_CACHE(apple80211_user_roam_cache*) = 0;
    virtual IOReturn setWCL_SCAN_ABORT(void*) = 0;
    virtual IOReturn setWCL_REAL_TIME_MODE(apple80211_wcl_real_time_mode*) = 0;
    virtual IOReturn setWCL_ARP_MODE(apple80211_wcl_arp_mode*) = 0;
    virtual IOReturn setWCL_JOIN_ABORT(void*) = 0;
    virtual IOReturn setWCL_TRIGGER_CC(triggerCC*) = 0;
    virtual IOReturn setWCL_SCAN_REQ(apple80211ScanRequest*) = 0;
    virtual IOReturn setWCL_ASSOCIATE(apple80211AssocCandidates*) = 0;
    virtual IOReturn setWCL_QOS_PARAMS(apple80211_wcl_qos_params*) = 0;
    virtual IOReturn setWCL_LINK_UP_DONE(void*) = 0;
    virtual IOReturn setWCL_SET_SCAN_HOME_AWAY_TIME(scanHomeAndAwayTime*) = 0;
    virtual IOReturn setVOICE_IND_STATE(apple80211_voice_ind_state*) = 0;
    virtual IOReturn setWCL_LINK_STATE_UPDATE(apple80211_wcl_update_link_state*) = 0;
    virtual IOReturn setRSN_XE(apple80211_rsn_xe_data*) = 0;
    virtual IOReturn setWIFI_BT_5G_POLICY(apple80211_wifi_bt_5g_policy_t*) = 0;
    virtual IOReturn setWCL_ULOFDMA_STATE(apple80211_wcl_ulofdma_state*) = 0;
    virtual IOReturn setWCL_ACTION_FRAME(apple80211_wcl_action_frame*) = 0;
    virtual IOReturn setGAS_ABORT(void*) = 0;
    virtual IOReturn setOS_FEATURE_FLAGS(apple80211_feature_flags*) = 0;
    virtual IOReturn setDHCP_RENEWAL_DATA(apple80211_dhcp_renewal_data*) = 0;
    virtual IOReturn setBATTERY_POWERSAVE_CONFIG(apple80211_battery_ps_config*) = 0;
    virtual IOReturn setMIMO_CONFIG(apple80211_mimo_config*) = 0;
    virtual IOReturn setWCL_CONFIG_BG_MOTIONPROFILE(apple80211_bg_motion_profile*) = 0;
    virtual IOReturn setWCL_CONFIG_BG_NETWORK(apple80211_bg_network*) = 0;
    virtual IOReturn setWCL_CONFIG_BGSCAN(apple80211_bg_scan*) = 0;
    virtual IOReturn setWCL_CONFIG_BG_PARAMS(apple80211_bg_params*) = 0;
    virtual IOReturn setPOWER_PROFILE(apple80211_power_profile*) = 0;
    virtual IOReturn setHEARTBEAT(void*) = 0;
    virtual IOReturn setINTERFACE_SETTING(apple80211_interface_setting*) = 0;
    virtual IOReturn setBYPASS_TX_POWER_CAP(apple80211_bypass_tx_power_cap*) = 0;
    virtual IOReturn setFACETIME_WIFICALLING_PARAMS(apple80211_facetime_wificalling_params*) = 0;
    virtual IOReturn setIPV4_PARAMS(apple80211_ipv4_params*) = 0;
    virtual IOReturn setWCL_WNM_OPS(apple80211_wcl_wnm_config_t*) = 0;
    virtual IOReturn setWCL_WNM_OFFLOAD(apple80211_wcl_wnm_offload_t*) = 0;
    virtual IOReturn setWCL_LIMITED_AGGREGATION(apple80211_limited_aggregation_config*) = 0;
    virtual IOReturn setWCL_BCN_MUTE_CONFIG(apple80211_bcn_mute_config*) = 0;
    virtual IOReturn setEAP_FILTER_CONFIG(apple80211_eap_filter_config*) = 0;
    virtual IOReturn setWOW_LOW_POWER_MODE(apple80211_wow_low_power_mode*) = 0;
    virtual IOReturn setDUAL_POWER_MODE(apple80211_dual_power_mode_params*) = 0;
    virtual IOReturn setWCL_UPDATE_FAST_LANE(apple80211_fastlane*) = 0;
    virtual IOReturn setWCL_ASSOCIATED_SLEEP(apple80211_associated_sleep_config*) = 0;
    virtual IOReturn setCONGESTION_CTRL_IND(apple80211_congestion_control_indication*) = 0;
    virtual IOReturn setSTAND_ALONE_MODE_STATE(apple80211_standalone_state*) = 0;
    virtual IOReturn setIPV6_PARAMS(apple80211_ipv6_params*) = 0;
    virtual IOReturn setINFRA_ENUMERATED(apple80211_infra_enumerated*) = 0;
    virtual IOReturn setLMTPC_CONFIG(apple80211_lmtpc_config*) = 0;
    virtual IOReturn setTRAFFIC_ENG_PARAMS(apple80211_traffic_eng_params*) = 0;
    virtual IOReturn setLE_SCAN_PARAM(apple80211_le_scan_params*) = 0;
    virtual IOReturn setTIMESYNC_GPIO(apple80211_timesync_gpio*) = 0;
    virtual IOReturn setHOST_CLOCK_INFO(apple80211_host_clock_info*) = 0;
    virtual IOReturn setFW_CLOCK_SOURCE(apple80211_fw_clock_source*) = 0;
    virtual IOReturn setTIMESYNC_TX_POLICY(apple80211_timesync_tx_policy*) = 0;
    virtual IOReturn setTIMESYNC_RX_POLICY(apple80211_timesync_rx_policy*) = 0;
    virtual IOReturn setTIMESTAMPING_EN(apple80211_timestamping_en*) = 0;
    virtual IOReturn setWCL_SOI_CONFIG(appl80211_sleep_on_inactivity_config*) = 0;
    virtual IOReturn setMWS_TIME_SHARING_WIFI_ENH(apple80211_mws_time_sharing*) = 0;
    virtual IOReturn setMWS_WIFI_TYPE_7_BITMAP_WIFI_ENH(apple80211_mws_wifi_channel_bitmap*) = 0;
    virtual IOReturn setMWS_COEX_BITMAP_WIFI_ENH(apple80211_mws_wifi_channel_bitmap*) = 0;
    virtual IOReturn setMWS_DISABLE_OCL_BITMAP_WIFI_ENH(apple80211_mws_wifi_channel_bitmap*) = 0;
    virtual IOReturn setMWS_RFEM_CONFIG_WIFI_ENH(apple80211_mws_rfem_config*) = 0;
    virtual IOReturn setMWS_ASSOC_PROTECTION_BITMAP_WIFI_ENH(apple80211_mws_wifi_channel_bitmap*) = 0;
    virtual IOReturn setMWS_SCAN_FREQ_WIFI_ENH(apple80211_mws_scan_freq*) = 0;
    virtual IOReturn setMWS_SCAN_FREQ_MODE_WIFI_ENH(apple80211_mws_scan_freq_mode*) = 0;
    virtual IOReturn setMWS_CONDITION_ID_BITMAP_WIFI_ENH(apple80211_mws_condition_id_config*) = 0;
    virtual IOReturn setMWS_ANTENNA_SELECTION_WIFI_ENH(apple80211_mws_antenna_selection*) = 0;
    virtual IOReturn setNDD_REQ(apple80211_ndd_data*) = 0;
    virtual IOReturn setDBRG_ENTROPY(apple80211_drbg_entropy*) = 0;
    virtual IOReturn setSDB_ENABLE(apple80211_sdb_enable*) = 0;
    virtual IOReturn setMWS_ACCESSORY_POWER_LIMIT_WIFI_ENH(apple80211_mws_accessory_power_limit*) = 0;
};
static_assert(sizeof(IO80211InfraProtocol) == 0x120, "Sequoia ABI size");
#endif
